"""PlatformIO pre-build script: embed webui/index.html into the firmware.

Gzips the page and writes webui_page.h (gitignored, regenerated every build)
holding one byte array: a complete HTTP response header (Content-Encoding:
gzip, Content-Length) followed by the gzipped page. dataserver.cpp's "/"
handler sends it straight from flash (FLAG_CUSTOM_HEADER), so the web UI
ships inside firmware.bin and is updated by pull-OTA like any other code -
no SPIFFS upload over USB.
"""

Import("env")  # noqa: F821

import gzip
import os

src_dir = env.subst("$PROJECT_SRC_DIR")  # noqa: F821
page = os.path.join(src_dir, "webui", "index.html")
out = os.path.join(src_dir, "webui_page.h")

with open(page, "rb") as f:
    html = f.read()
# mtime=0: identical input -> identical bytes, so an unchanged page doesn't
# rewrite the header and trigger a rebuild of dataserver.cpp
body = gzip.compress(html, compresslevel=9, mtime=0)
head = (
    "HTTP/1.1 200 OK\r\n"
    "Content-Type: text/html; charset=utf-8\r\n"
    "Content-Encoding: gzip\r\n"
    "Cache-Control: no-cache\r\n"
    "Connection: close\r\n"
    "Content-Length: %d\r\n\r\n" % len(body)
).encode()
data = head + body

lines = ["// Generated by webui_gen.py from webui/index.html - do not edit.",
         "#pragma once",
         "static const uint8_t WEBUI_PAGE[] = {"]
for i in range(0, len(data), 20):
    lines.append("  " + ",".join(str(b) for b in data[i:i + 20]) + ",")
lines += ["};", ""]
text = "\n".join(lines)

old = open(out).read() if os.path.exists(out) else None
if old != text:
    with open(out, "w") as f:
        f.write(text)
print("[webui] %s: %d B html -> %d B gzip (+%d B header)" % (page, len(html), len(body), len(head)))
